package modes

import "github.com/jdpalmer/jem/app"

var modeTable = []app.ModeInfo{
	{
		Mode:              app.LModeNone,
		DisplayName:       "Text",
		CompletionName:    "text",
		SyntaxKind:        app.ModeSyntaxNone,
		SyntaxFlags:       app.ModeFlagCommentSlashLine | app.ModeFlagCommentSlashBlock,
		CommentOpen:       "/*",
		CommentAltOpen:    "//",
		CommentAppend:     "  /* */",
		CommentCursorBack: 3,
	},
	{
		Mode:              app.LModeC,
		DisplayName:       "C",
		CompletionName:    "c",
		SyntaxKind:        app.ModeSyntaxGeneral,
		SyntaxFlags:       app.ModeFlagCommentSlashLine | app.ModeFlagCommentSlashBlock | app.ModeFlagPreprocHashAtBOL,
		CommentOpen:       "/*",
		CommentAltOpen:    "//",
		CommentAppend:     "  /* */",
		CommentCursorBack: 3,
	},
	{
		Mode:           app.LModeJava,
		DisplayName:    "Java",
		CompletionName: "java",
		SyntaxKind:     app.ModeSyntaxGeneral,
		SyntaxFlags:    app.ModeFlagCommentSlashLine | app.ModeFlagCommentSlashBlock,
		CommentOpen:    "/*",
		CommentAltOpen: "//",
	},
	{
		Mode:           app.LModePython,
		DisplayName:    "Python",
		CompletionName: "python",
		SyntaxKind:     app.ModeSyntaxGeneral,
		SyntaxFlags:    app.ModeFlagCommentHash,
		CommentOpen:    "#",
		CommentAppend:  "  # ",
	},
	{
		Mode:           app.LModeLua,
		DisplayName:    "Lua",
		CompletionName: "text",
		SyntaxKind:     app.ModeSyntaxGeneral,
		SyntaxFlags:    app.ModeFlagCommentLua,
		CommentOpen:    "--",
		CommentAppend:  "  -- ",
	},
	{
		Mode:           app.LModeLisp,
		DisplayName:    "Lisp",
		CompletionName: "text",
		SyntaxKind:     app.ModeSyntaxGeneral,
		SyntaxFlags:    app.ModeFlagIdentLispExtra | app.ModeFlagIdentLispSigil | app.ModeFlagCommentSemi,
		CommentOpen:    ";",
		CommentAppend:  "  ; ",
	},
	{
		Mode:              app.LModeMarkdown,
		DisplayName:       "Markdown",
		CompletionName:    "text",
		SyntaxKind:        app.ModeSyntaxMarkdown,
		CommentOpen:       "<!--",
		CommentAppend:     "  <!--  -->",
		CommentCursorBack: 4,
	},
	{
		Mode:              app.LModePascal,
		DisplayName:       "Pascal",
		CompletionName:    "text",
		SyntaxKind:        app.ModeSyntaxGeneral,
		SyntaxFlags:       app.ModeFlagCommentPascalBrace | app.ModeFlagCommentPascalParen | app.ModeFlagNoCurlyRainbow,
		CommentOpen:       "{",
		CommentAppend:     "  {  }",
		CommentCursorBack: 2,
	},
	{
		Mode:           app.LModeVerilog,
		DisplayName:    "Verilog",
		CompletionName: "text",
		SyntaxKind:     app.ModeSyntaxGeneral,
		SyntaxFlags:    app.ModeFlagCommentSlashLine | app.ModeFlagCommentSlashBlock,
		CommentOpen:    "/*",
		CommentAltOpen: "//",
	},
	{
		Mode:           app.LModeMake,
		DisplayName:    "Make",
		CompletionName: "text",
		SyntaxKind:     app.ModeSyntaxHashCommentOnly,
		SyntaxFlags:    app.ModeFlagCommentHash,
		CommentOpen:    "#",
		CommentAppend:  "  # ",
	},
	{
		Mode:           app.LModeSwift,
		DisplayName:    "Swift",
		CompletionName: "swift",
		SyntaxKind:     app.ModeSyntaxGeneral,
		SyntaxFlags:    app.ModeFlagCommentSlashLine | app.ModeFlagCommentSlashBlock | app.ModeFlagPreprocHashAtBOL,
		CommentOpen:    "/*",
		CommentAltOpen: "//",
	},
	{
		Mode:           app.LModeJavaScript,
		DisplayName:    "JavaScript",
		CompletionName: "javascript",
		SyntaxKind:     app.ModeSyntaxGeneral,
		SyntaxFlags:    app.ModeFlagCommentSlashLine | app.ModeFlagCommentSlashBlock,
		CommentOpen:    "/*",
		CommentAltOpen: "//",
	},
	{
		Mode:           app.LModeActionScript,
		DisplayName:    "ActionScript",
		CompletionName: "javascript",
		SyntaxKind:     app.ModeSyntaxGeneral,
		SyntaxFlags:    app.ModeFlagCommentSlashLine | app.ModeFlagCommentSlashBlock,
		CommentOpen:    "/*",
		CommentAltOpen: "//",
	},
	{
		Mode:           app.LModeTypeScript,
		DisplayName:    "TypeScript",
		CompletionName: "typescript",
		SyntaxKind:     app.ModeSyntaxGeneral,
		SyntaxFlags:    app.ModeFlagCommentSlashLine | app.ModeFlagCommentSlashBlock,
		CommentOpen:    "/*",
		CommentAltOpen: "//",
	},
	{
		Mode:           app.LModeDart,
		DisplayName:    "Dart",
		CompletionName: "dart",
		SyntaxKind:     app.ModeSyntaxGeneral,
		SyntaxFlags:    app.ModeFlagCommentSlashLine | app.ModeFlagCommentSlashBlock,
		CommentOpen:    "/*",
		CommentAltOpen: "//",
	},
	{
		Mode:           app.LModeGo,
		DisplayName:    "Go",
		CompletionName: "go",
		SyntaxKind:     app.ModeSyntaxGeneral,
		SyntaxFlags:    app.ModeFlagCommentSlashLine | app.ModeFlagCommentSlashBlock,
		CommentOpen:    "/*",
		CommentAltOpen: "//",
	},
	{
		Mode:           app.LModeCSharp,
		DisplayName:    "C#",
		CompletionName: "csharp",
		SyntaxKind:     app.ModeSyntaxGeneral,
		SyntaxFlags:    app.ModeFlagCommentSlashLine | app.ModeFlagCommentSlashBlock | app.ModeFlagPreprocHashAtBOL,
		CommentOpen:    "/*",
		CommentAltOpen: "//",
	},
	{
		Mode:           app.LModeRust,
		DisplayName:    "Rust",
		CompletionName: "rust",
		SyntaxKind:     app.ModeSyntaxGeneral,
		SyntaxFlags:    app.ModeFlagCommentSlashLine | app.ModeFlagCommentSlashBlock,
		CommentOpen:    "/*",
		CommentAltOpen: "//",
	},
	{
		Mode:           app.LModeR,
		DisplayName:    "R",
		CompletionName: "r",
		SyntaxKind:     app.ModeSyntaxGeneral,
		SyntaxFlags:    app.ModeFlagCommentHash,
		CommentOpen:    "#",
		CommentAppend:  "  # ",
	},
	{
		Mode:           app.LModeKotlin,
		DisplayName:    "Kotlin",
		CompletionName: "kotlin",
		SyntaxKind:     app.ModeSyntaxGeneral,
		SyntaxFlags:    app.ModeFlagCommentSlashLine | app.ModeFlagCommentSlashBlock,
		CommentOpen:    "/*",
		CommentAltOpen: "//",
	},
	{
		Mode:              app.LModeHTML,
		DisplayName:       "HTML/XML",
		CompletionName:    "html",
		SyntaxKind:        app.ModeSyntaxHTML,
		CommentOpen:       "<!--",
		CommentAppend:     "  <!--  -->",
		CommentCursorBack: 4,
	},
	{
		Mode:              app.LModeCSS,
		DisplayName:       "CSS",
		CompletionName:    "css",
		SyntaxKind:        app.ModeSyntaxGeneral,
		SyntaxFlags:       app.ModeFlagIdentDash | app.ModeFlagCommentSlashBlock | app.ModeFlagAtRule,
		CommentOpen:       "/*",
		CommentAppend:     "  /* */",
		CommentCursorBack: 3,
	},
}

func LangModeInfo(mode app.LangMode) *app.ModeInfo {
	for i := range modeTable {
		if modeTable[i].Mode == mode {
			return &modeTable[i]
		}
	}
	return &modeTable[0]
}
