package modes

import "github.com/jdpalmer/jem/session"

var modeTable = []session.ModeInfo{
	{
		Mode:              session.LModeNone,
		DisplayName:       "Text",
		CompletionName:    "text",
		SyntaxKind:        session.ModeSyntaxNone,
		SyntaxFlags:       session.ModeFlagCommentSlashLine | session.ModeFlagCommentSlashBlock,
		CommentOpen:       "/*",
		CommentAltOpen:    "//",
		CommentAppend:     "  /* */",
		CommentCursorBack: 3,
	},
	{
		Mode:              session.LModeC,
		DisplayName:       "C",
		CompletionName:    "c",
		SyntaxKind:        session.ModeSyntaxGeneral,
		SyntaxFlags:       session.ModeFlagCommentSlashLine | session.ModeFlagCommentSlashBlock | session.ModeFlagPreprocHashAtBOL,
		CommentOpen:       "/*",
		CommentAltOpen:    "//",
		CommentAppend:     "  /* */",
		CommentCursorBack: 3,
	},
	{
		Mode:           session.LModeJava,
		DisplayName:    "Java",
		CompletionName: "java",
		SyntaxKind:     session.ModeSyntaxGeneral,
		SyntaxFlags:    session.ModeFlagCommentSlashLine | session.ModeFlagCommentSlashBlock,
		CommentOpen:    "/*",
		CommentAltOpen: "//",
	},
	{
		Mode:           session.LModePython,
		DisplayName:    "Python",
		CompletionName: "python",
		SyntaxKind:     session.ModeSyntaxGeneral,
		SyntaxFlags:    session.ModeFlagCommentHash,
		CommentOpen:    "#",
		CommentAppend:  "  # ",
	},
	{
		Mode:           session.LModeLua,
		DisplayName:    "Lua",
		CompletionName: "text",
		SyntaxKind:     session.ModeSyntaxGeneral,
		SyntaxFlags:    session.ModeFlagCommentLua,
		CommentOpen:    "--",
		CommentAppend:  "  -- ",
	},
	{
		Mode:           session.LModeLisp,
		DisplayName:    "Lisp",
		CompletionName: "text",
		SyntaxKind:     session.ModeSyntaxGeneral,
		SyntaxFlags:    session.ModeFlagIdentLispExtra | session.ModeFlagIdentLispSigil | session.ModeFlagCommentSemi,
		CommentOpen:    ";",
		CommentAppend:  "  ; ",
	},
	{
		Mode:              session.LModeMarkdown,
		DisplayName:       "Markdown",
		CompletionName:    "text",
		SyntaxKind:        session.ModeSyntaxMarkdown,
		CommentOpen:       "<!--",
		CommentAppend:     "  <!--  -->",
		CommentCursorBack: 4,
	},
	{
		Mode:              session.LModePascal,
		DisplayName:       "Pascal",
		CompletionName:    "text",
		SyntaxKind:        session.ModeSyntaxGeneral,
		SyntaxFlags:       session.ModeFlagCommentPascalBrace | session.ModeFlagCommentPascalParen | session.ModeFlagNoCurlyRainbow,
		CommentOpen:       "{",
		CommentAppend:     "  {  }",
		CommentCursorBack: 2,
	},
	{
		Mode:           session.LModeVerilog,
		DisplayName:    "Verilog",
		CompletionName: "text",
		SyntaxKind:     session.ModeSyntaxGeneral,
		SyntaxFlags:    session.ModeFlagCommentSlashLine | session.ModeFlagCommentSlashBlock,
		CommentOpen:    "/*",
		CommentAltOpen: "//",
	},
	{
		Mode:           session.LModeMake,
		DisplayName:    "Make",
		CompletionName: "text",
		SyntaxKind:     session.ModeSyntaxHashCommentOnly,
		SyntaxFlags:    session.ModeFlagCommentHash,
		CommentOpen:    "#",
		CommentAppend:  "  # ",
	},
	{
		Mode:           session.LModeSwift,
		DisplayName:    "Swift",
		CompletionName: "swift",
		SyntaxKind:     session.ModeSyntaxGeneral,
		SyntaxFlags:    session.ModeFlagCommentSlashLine | session.ModeFlagCommentSlashBlock | session.ModeFlagPreprocHashAtBOL,
		CommentOpen:    "/*",
		CommentAltOpen: "//",
	},
	{
		Mode:           session.LModeJavaScript,
		DisplayName:    "JavaScript",
		CompletionName: "javascript",
		SyntaxKind:     session.ModeSyntaxGeneral,
		SyntaxFlags:    session.ModeFlagCommentSlashLine | session.ModeFlagCommentSlashBlock,
		CommentOpen:    "/*",
		CommentAltOpen: "//",
	},
	{
		Mode:           session.LModeActionScript,
		DisplayName:    "ActionScript",
		CompletionName: "javascript",
		SyntaxKind:     session.ModeSyntaxGeneral,
		SyntaxFlags:    session.ModeFlagCommentSlashLine | session.ModeFlagCommentSlashBlock,
		CommentOpen:    "/*",
		CommentAltOpen: "//",
	},
	{
		Mode:           session.LModeTypeScript,
		DisplayName:    "TypeScript",
		CompletionName: "typescript",
		SyntaxKind:     session.ModeSyntaxGeneral,
		SyntaxFlags:    session.ModeFlagCommentSlashLine | session.ModeFlagCommentSlashBlock,
		CommentOpen:    "/*",
		CommentAltOpen: "//",
	},
	{
		Mode:           session.LModeDart,
		DisplayName:    "Dart",
		CompletionName: "dart",
		SyntaxKind:     session.ModeSyntaxGeneral,
		SyntaxFlags:    session.ModeFlagCommentSlashLine | session.ModeFlagCommentSlashBlock,
		CommentOpen:    "/*",
		CommentAltOpen: "//",
	},
	{
		Mode:           session.LModeGo,
		DisplayName:    "Go",
		CompletionName: "go",
		SyntaxKind:     session.ModeSyntaxGeneral,
		SyntaxFlags:    session.ModeFlagCommentSlashLine | session.ModeFlagCommentSlashBlock,
		CommentOpen:    "/*",
		CommentAltOpen: "//",
	},
	{
		Mode:           session.LModeCSharp,
		DisplayName:    "C#",
		CompletionName: "csharp",
		SyntaxKind:     session.ModeSyntaxGeneral,
		SyntaxFlags:    session.ModeFlagCommentSlashLine | session.ModeFlagCommentSlashBlock | session.ModeFlagPreprocHashAtBOL,
		CommentOpen:    "/*",
		CommentAltOpen: "//",
	},
	{
		Mode:           session.LModeRust,
		DisplayName:    "Rust",
		CompletionName: "rust",
		SyntaxKind:     session.ModeSyntaxGeneral,
		SyntaxFlags:    session.ModeFlagCommentSlashLine | session.ModeFlagCommentSlashBlock,
		CommentOpen:    "/*",
		CommentAltOpen: "//",
	},
	{
		Mode:           session.LModeR,
		DisplayName:    "R",
		CompletionName: "r",
		SyntaxKind:     session.ModeSyntaxGeneral,
		SyntaxFlags:    session.ModeFlagCommentHash,
		CommentOpen:    "#",
		CommentAppend:  "  # ",
	},
	{
		Mode:           session.LModeKotlin,
		DisplayName:    "Kotlin",
		CompletionName: "kotlin",
		SyntaxKind:     session.ModeSyntaxGeneral,
		SyntaxFlags:    session.ModeFlagCommentSlashLine | session.ModeFlagCommentSlashBlock,
		CommentOpen:    "/*",
		CommentAltOpen: "//",
	},
	{
		Mode:              session.LModeHTML,
		DisplayName:       "HTML/XML",
		CompletionName:    "html",
		SyntaxKind:        session.ModeSyntaxHTML,
		CommentOpen:       "<!--",
		CommentAppend:     "  <!--  -->",
		CommentCursorBack: 4,
	},
	{
		Mode:              session.LModeCSS,
		DisplayName:       "CSS",
		CompletionName:    "css",
		SyntaxKind:        session.ModeSyntaxGeneral,
		SyntaxFlags:       session.ModeFlagIdentDash | session.ModeFlagCommentSlashBlock | session.ModeFlagAtRule,
		CommentOpen:       "/*",
		CommentAppend:     "  /* */",
		CommentCursorBack: 3,
	},
}

func LangModeInfo(mode session.LangMode) *session.ModeInfo {
	for i := range modeTable {
		if modeTable[i].Mode == mode {
			return &modeTable[i]
		}
	}
	return &modeTable[0]
}
